### ISSUE TITLE
Climate data and subsetting 2020 data

### ISSUE THREAD

**Issue by ChristinaB** [waterhackweek/whw2020_covidcrew#20]
@pranjalirai @Castronova 

Let's start with 

- [ ] this shapefile https://www.hydroshare.org/resource/f7fb829606f643a2bf0b710b4e3d07e1/

and then download the time series with RENCI and CUAHSI help  -

**Comment by pranjalirai** [comment]
I would love to learn more. I cannot access the shapefile though.
